### ISSUE TITLE
Typo in 4.6.1

### ISSUE THREAD

**Issue by AlexanderMoerseburg** [laderast/bash_for_bioinformatics#2]
Dear Ted (if I may),
first, thanks for providing this resource.

I think you have a typo in section 4.6.1 (https://laderast.github.io/bash_for_bioinformatics/03-cloud-computing-basics.html#running-scripts-on-a-worker-is-indirect)

I think

> Transfer results file back to the worker.

Should read:

> Transfer results file back to project storage.

Best, Alex

**Comment by laderast** [comment]
Thank you, @AlexanderMoerseburg  for catching this. I will fix this

**Comment by laderast** [comment]
Now fixed: https://laderast.github.io/bash_for_bioinformatics/03-cloud-computing-basics.html#running-scripts-on-a-worker-is-indirect
