### ISSUE TITLE
Some difficulties with using regenie in UKB RAP

### ISSUE THREAD

**Issue by wojiaolianer** [laderast/bash_for_bioinformatics#3]
Hello,
I met with some difficulties with using UKB RAP. An error in runing burden test with UKB RAP: "Detected 1 masks with unknown annotations". I find someone with same problem in github, with the instruction, I have already convert masks file to LF line break (Unix) and confirm all masks present in anno file, but still get same error. I have tried for dozens of times, but it failed to run. What's more, I can run test data in linux servers sucessfully, I don't know what went wrong.

**Comment by laderast** [comment]
Hi @wojiaolianer - can you please ask this question at community.dnanexus.com - they will be able to help you.
