### ISSUE TITLE
A couple minor scripting basics updates

### ISSUE THREAD

**Issue by jashapiro** [laderast/bash_for_bioinformatics#4]
Hi Ted-

Saw your post on Twitter about this updated material, so I thought I would check it out. Very nice! I did have a couple of things I noticed as I was scanning through, so I thought I would submit an issue. (I would have replied on twitter, or sent a message there, but you don't follow me yet, so here I am.)

First thing was a missing end of a sentence here: 
https://github.com/laderast/bash_for_bioinformatics/blob/9d5ffddae755647e4f5c85eedaa2fd60b73c74d1/02-scripting-basics.qmd#L312

I assume you mean something like "...between the variable, equals sign, and value."

The other thing is a bit more subtle: 
https://github.com/laderast/bash_for_bioinformatics/blob/9d5ffddae755647e4f5c85eedaa2fd60b73c74d1/02-scripting-basics.qmd#L322-L329

In the case you show `"$my_var.vcf.gz"` will actually work just fine and return `chr1.vcf.gz`, as a period can't be part of a variable name. The trouble comes when want something like `chr1_1.vcf.gz` as the output, in which case `"$my_var_1.vcf.gz"` will result in the use of an undefined variable, so you will get `.vcf.gz` as the output unless you do `"${my_var}_1.vcf.gz"`. 

In either case though, I surely agree with your recommendation to use brackets in bash variables!

**Comment by laderast** [comment]
Thanks for catching these @jashapiro - I will fix. I'm always learning more about Bash!

**Comment by laderast** [comment]
Fixed. I ended up using your example: https://laderast.github.io/bash_for_bioinformatics/02-scripting-basics.html#sec-bash-variables

And also you have an acknowledgement: https://laderast.github.io/bash_for_bioinformatics/#contributors

**Comment by jashapiro** [comment]
Thanks Ted! looks great.
